require('./util.js');
require('./alert.js');
require('./button.js');
require('./carousel.js');
require('./collapse.js');
require('./dropdown.js');
require('./modal.js');
require('./scrollspy.js');
require('./tab.js');
require('./tooltip.js');
require('./popover.js')